### ISSUE TITLE
Bottom half of "Apply" Button in Settings Panel is not clickable

### ISSUE THREAD

**Issue by PJang94** [Stateware/Dav3i#12]
1. Open browser.
2. Go to http://usve74985.serverprofi24.com/
3. Click Begin when the page is done loading.
4. Click Settings.
5. Change Start Year to 1990.
6. Click anywhere in the bottom half of "Apply" button.

Expected: The Start Year on the graphs changes to 1990.
Observed: The button is not clicked, and the year does not change.

**Comment by Googleguy22** [comment]
@PJang94 I like your work especially the magician project.  But where are the database files for that project? I would like to interview for a role in my Startup in Bay Area. Get back to me with your email after updating your Magician repository with the required Database files.

**Comment by Googleguy22** [comment]
Email me this working project asap at googleguy22@mail.com. Email the project functionality and features required only as part of the PDF http://www.megafileupload.com/Z09/Project.pdf  Remember that it should be working and completely organized.

**Comment by Googleguy22** [comment]
Instead what you can do is just email me the entire project as you did for your homework in two parts- the initial phase and final if that makes it easy.

**Comment by Googleguy22** [comment]
@PJang94 Instead what you can do is just email me the entire project as you did for your homework in two parts- the initial phase and final if that makes it easy.
