### ISSUE TITLE
You can type characters into the years boxes with no error

### ISSUE THREAD

**Issue by kylejn27** [Stateware/Dav3i#13]
To reproduce:
1. Open chrome browser
2. Go to http://usve74985.serverprofi24.com/
3. Click Begin when the page is done loading
4. Click Settings
5. Enter amount of characters into the "Start Year:" or "End Year:" text boxes
6. Click Apply

**Comment by jcrafts318** [comment]
Still needa fix as of 4/27

**Comment by kylejn27** [comment]
fixed
