### ISSUE TITLE
Switching from Regional to Combined

### ISSUE THREAD

**Issue by NicholasDenaro** [Stateware/Dav3i#4]
Switching from regional to combined view leaves regional graphs in view.

Steps to reproduce:
1. Open the browser.
2. Go to http://usve74985.serverprofi24.com/
3. Wait for the Begin button to appear and click it.
4. Click on 2+ different regions.
5. Click Advanced Settings and click Combined.
6. (Optional) Close the Advanced Settings.

Expected: One graph with the regions all together
Observed: One graph displaying the combined statistics, other old graphs displaying regional statistics

**Comment by jcrafts318** [comment]
This is fixed
