### ISSUE TITLE
Graphs not displaying correctly

### ISSUE THREAD

**Issue by WBittner** [Stateware/Dav3i#5]
I receive no graphs if the first country I click on has no data. Then, clicking and unclicking countries(assuming you start by unclicking the no data country) appears to have very interesting effect. I'm not really sure what is going on but it is definitely not correct.

Steps to reproduce: 
1: Open up webpage in browser. 
2: Click on Greenland (or any country that has no data - grey on map)
3: Click on any other country who does have data. 
Optional: Click on multiple more countries. 
                Unclick Greenland
                Start randomly clicking/unclicking other countries

Expected result: Graphs display for countries that have data.
Observed result: No graphs until you unclick Greenland. Then you get one graph. Even if you have multiple selected. Then if you click/unclick other graphs are added.

**Comment by jcrafts318** [comment]
Same cause as issue #7. We are actively working on this currently

**Comment by jcrafts318** [comment]
This has been fixed
