### ISSUE TITLE
Reload page does not update graph type

### ISSUE THREAD

**Issue by NicholasDenaro** [Stateware/Dav3i#6]
Steps to reproduce:
1. Open Browser.
2. Go to http://usve74985.serverprofi24.com/
3. Click "Begin" when the page is done loading.
4. Click "Advanced Settings".
5. Select "Combined".
6. Click "Close".
7. Refresh the page.
8. Click "Begin" when the page is done loading.
9. Click "Advanced Settings". Note that "Combined" is still selected.
10. Click "Close".
11. Select 2+ countries.

Expected: Graph is of combined type (or "Regional" should be selected in "Advanced Settings").
Observed: Graphs are of regional type.

**Comment by jcrafts318** [comment]
Will fix this in today's meeting.

**Comment by jcrafts318** [comment]
Still needs fix as of 4/27

**Comment by kylejn27** [comment]
I went through repro steps. The bug does not happen for me. I'm using chrome. I think my redo of the settings menu fixed this.  

I would like somebody to confirm with me that this is fixed before closing it.
