### ISSUE TITLE
Graphs not displaying and clear not working

### ISSUE THREAD

**Issue by NicholasDenaro** [Stateware/Dav3i#7]
Steps to reproduce:
1. Open the Browser.
2. Go to http://usve74985.serverprofi24.com/
3. Click on "Begin".
4. Select the following countries in order:
    - United States
    - Canada
    - Mexico
    - Greenland
    - Spain
    - France
    - Germany
    - Egypt
    - Sudan
    - Libya
5. Note the countries which display graphs:
    - United States
    - Mexico
    - Canada
    - Egypt
    - Sudan
    - Libya
6. Click "Clear"
7. Note the countries which are selected:
    - United States
    - Canada
    - Egypt
    - Sudan
    - Libya
8. Deselect Greenland
9. Note the countries which display graphs:
    - United States
    - Mexico
    - Canada
    - Egypt
    - Sudan
    - Libya
    - France
10. Click "Clear"
11. Note the countries which display graphs:
    - Spain

**Comment by jcrafts318** [comment]
We are actively working on this currently

**Comment by jcrafts318** [comment]
This has been fixed
