### ISSUE TITLE
Heat Map not displaying correct information

### ISSUE THREAD

**Issue by WBittner** [Stateware/Dav3i#8]
When you change the stat tab to a new tab and then hover over the heatmap, the heatmaps wording will change, but the number displayed is still the deaths count. Pretty morbid.

Steps to reproduce:
1. Open page. 
2. Hover over a country.
3. Click on a new stat tab.
4. Hover over same country.

Expected result: New tooltip with new stat name and relevant statistic
Observed result: New tooltip with new stat name and the number of deaths statistic.

**Comment by jcrafts318** [comment]
We are actively working on this currently

**Comment by jcrafts318** [comment]
This has been fixed
