### ISSUE TITLE
Cannot exit settings screen if entered year outside range

### ISSUE THREAD

**Issue by CarpeDiEmma** [Stateware/Dav3i#9]
If you change Start year, End year, or Heat Map year, to a year outside the data's time span, you cannot exit the settings screen (and there is no error warning that appears).

Repro Steps:
1. Open Dav3i
2. Click Advanced settings
3. Change Start year to 1979
Expected: Warning or change based on invalid date, allows you to leave settings window
Observed: No warning and not able to leave setting window

**Comment by jcrafts318** [comment]
This has been fixed
